# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-west-1
      AWS_EC2_METADATA_DISABLED: true

    services:
      localstack:
        image: localstack/localstack:latest   # ✅ etiqueta válida
        env:
          SERVICES: s3
          AWS_DEFAULT_REGION: eu-west-1
          DEBUG: "1"
        ports:
          - 4566:4566
        options: >-
          --health-cmd="sh -c \"curl -fsS http://localhost:4566/_localstack/health | grep -E '\\\"s3\\\"\\s*:\\s*\\\"running\\\"' || exit 1\""
          --health-interval=5s --health-retries=60 --health-timeout=5s

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: ci/requirements.txt

      - name: Install deps
        run: pip install -r ci/requirements.txt awscli-local

      - name: Unit tests (exclude integration)
        run: |
          mkdir -p reports
          pytest -m "not integration" -n auto --junitxml=reports/junit-unit.xml

      - name: Wait for LocalStack S3 (HTTP)
        run: |
          for i in $(seq 1 60); do
            if curl -fsS http://localhost:4566/_localstack/health | grep -E '"s3"\s*:\s*"running"'; then
              echo "LocalStack S3 listo."
              break
            fi
            sleep 2
          done
          curl -fsS http://localhost:4566/_localstack/health || true

      - name: Prepare LocalStack S3
        run: |
          ENDPOINT=http://localhost:4566
          BUCKET=company-transfer-ci-artifacts
          awslocal --endpoint-url=$ENDPOINT s3api head-bucket --bucket "$BUCKET" \
            || awslocal --endpoint-url=$ENDPOINT s3api create-bucket --bucket "$BUCKET" \
                 --create-bucket-configuration LocationConstraint=$AWS_DEFAULT_REGION
          awslocal --endpoint-url=$ENDPOINT s3 ls

      - name: Publish reports to LocalStack S3
        env:
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          ENDPOINT=http://localhost:4566
          BUCKET=company-transfer-ci-artifacts
          REPO=company-transfer-money-service
          BRANCH="${GITHUB_REF_NAME}"
          COMMIT="${GITHUB_SHA}"
          CI_SYSTEM=github
          PREFIX="s3://${BUCKET}/${REPO}/${BRANCH}/${COMMIT}/${CI_SYSTEM}"
          [ -f reports/junit-unit.xml ] && awslocal --endpoint-url=$ENDPOINT s3 cp reports/junit-unit.xml "${PREFIX}/unit/junit-unit.xml" || true
          [ -d reports ] && awslocal --endpoint-url=$ENDPOINT s3 sync reports "${PREFIX}/reports" || true

      - name: Upload local artifact (opcional)
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/**
